-- Test data for QR scanning functionality
-- This creates a demo user that can be found by QR scanner

-- Insert demo user for QR testing
INSERT INTO users (
    id,
    email,
    full_name,
    username,
    bio,
    role,
    skill_level,
    rank,
    total_wins,
    total_losses,
    total_tournaments,
    elo_rating,
    spa_points,
    total_prize_pool,
    is_verified,
    is_active,
    user_code,
    qr_data,
    qr_generated_at,
    created_at,
    updated_at
) VALUES (
    'demo-user-123',
    'demo@saboarena.com',
    'Nguyễn Văn Demo',
    'demo_user',
    'Demo user for QR testing - Thích đánh cờ và giao lưu',
    'player',
    'intermediate',
    'Intermediate',
    15,
    8,
    5,
    1450,
    250,
    500000.0,
    true,
    true,
    'SABO123456',
    'SABO123456',
    NOW(),
    NOW(),
    NOW()
) ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    email = EXCLUDED.email,
    username = EXCLUDED.username,
    bio = EXCLUDED.bio,
    skill_level = EXCLUDED.skill_level,
    rank = EXCLUDED.rank,
    elo_rating = EXCLUDED.elo_rating,
    user_code = EXCLUDED.user_code,
    qr_data = EXCLUDED.qr_data,
    updated_at = NOW();

-- Insert additional test users with different codes
INSERT INTO users (
    id,
    email,
    full_name,
    username,
    role,
    skill_level,
    rank,
    total_wins,
    total_losses,
    total_tournaments,
    elo_rating,
    spa_points,
    total_prize_pool,
    is_verified,
    is_active,
    user_code,
    qr_data,
    qr_generated_at,
    created_at,
    updated_at
) VALUES 
(
    'test-user-001',
    'test1@saboarena.com',
    'Trần Văn Test',
    'test_user_1',
    'player',
    'beginner',
    'Beginner',
    5,
    10,
    2,
    1200,
    100,
    0.0,
    false,
    true,
    'SABO000001',
    'SABO000001',
    NOW(),
    NOW(),
    NOW()
),
(
    'test-user-002',
    'test2@saboarena.com',
    'Lê Thị Quét',
    'test_user_2',
    'player',
    'advanced',
    'Advanced',
    25,
    5,
    8,
    1650,
    500,
    1200000.0,
    true,
    true,
    'SABO000002',
    'SABO000002',
    NOW(),
    NOW(),
    NOW()
)
ON CONFLICT (id) DO UPDATE SET
    full_name = EXCLUDED.full_name,
    email = EXCLUDED.email,
    username = EXCLUDED.username,
    skill_level = EXCLUDED.skill_level,
    rank = EXCLUDED.rank,
    elo_rating = EXCLUDED.elo_rating,
    user_code = EXCLUDED.user_code,
    qr_data = EXCLUDED.qr_data,
    updated_at = NOW();

-- Verify test data
SELECT 
    id,
    full_name,
    email,
    user_code,
    qr_data,
    skill_level,
    elo_rating
FROM users 
WHERE user_code IN ('SABO123456', 'SABO000001', 'SABO000002')
ORDER BY user_code;