import '../models/user_profile.dart';

/// Mock service để cung cấp dữ liệu demo cho opponent cards
class MockPlayerService {
  static List<UserProfile> getDemoPlayers() {
    return [
      UserProfile(
        id: 'demo-1',
        email: 'dang.khang@saboarena.com',
        fullName: 'Đặng Khang',
        displayName: 'Đặng Khang',
        username: 'admin_175796958',
        bio: 'Pro player tại SABO Arena',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
        role: 'player',
        skillLevel: 'advanced',
        rank: 'H+', // Hạng H+ thay vì "Nâng cao"
        totalWins: 46,
        totalLosses: 30,
        totalTournaments: 5,
        eloRating: 1982,
        spaPoints: 2500,
        totalPrizePool: 15000000,
        isVerified: true,
        isActive: true,
        location: 'TP. Hồ Chí Minh',
        createdAt: DateTime.now().subtract(const Duration(days: 365)),
        updatedAt: DateTime.now(),
      ),
      UserProfile(
        id: 'demo-2',
        email: 'nguyen.duc@saboarena.com',
        fullName: 'Nguyễn Đức Anh',
        displayName: 'Nguyễn Đức Anh',
        username: 'champion_duc',
        bio: 'Vô địch quận 1',
        avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face',
        role: 'player',
        skillLevel: 'professional',
        rank: 'G',
        totalWins: 84,
        totalLosses: 23,
        totalTournaments: 12,
        eloRating: 2156,
        spaPoints: 5200,
        totalPrizePool: 35000000,
        isVerified: true,
        isActive: true,
        location: 'Quận 1, TP.HCM',
        createdAt: DateTime.now().subtract(const Duration(days: 500)),
        updatedAt: DateTime.now(),
      ),
      UserProfile(
        id: 'demo-3',
        email: 'tran.minh@saboarena.com',
        fullName: 'Trần Minh Hoàng',
        displayName: 'Trần Minh Hoàng',
        username: 'hoang_billiards',
        bio: 'Học viên xuất sắc',
        avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
        role: 'player',
        skillLevel: 'intermediate',
        rank: 'I+',
        totalWins: 32,
        totalLosses: 28,
        totalTournaments: 3,
        eloRating: 1654,
        spaPoints: 1200,
        totalPrizePool: 8500000,
        isVerified: false,
        isActive: true,
        location: 'Quận 3, TP.HCM',
        createdAt: DateTime.now().subtract(const Duration(days: 180)),
        updatedAt: DateTime.now(),
      ),
      UserProfile(
        id: 'demo-4',
        email: 'le.van.nam@saboarena.com',
        fullName: 'Lê Văn Nam',
        displayName: 'Lê Văn Nam',
        username: 'nam_rookie',
        bio: 'Tài năng trẻ',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
        role: 'player',
        skillLevel: 'beginner',
        rank: 'K+',
        totalWins: 18,
        totalLosses: 22,
        totalTournaments: 1,
        eloRating: 1345,
        spaPoints: 650,
        totalPrizePool: 2000000,
        isVerified: false,
        isActive: true,
        location: 'Quận 7, TP.HCM',
        createdAt: DateTime.now().subtract(const Duration(days: 90)),
        updatedAt: DateTime.now(),
      ),
      UserProfile(
        id: 'demo-5',
        email: 'pham.thi.lan@saboarena.com',
        fullName: 'Phạm Thị Lan',
        displayName: 'Phạm Thị Lan',
        username: 'lan_pro',
        bio: 'Nữ hoàng billiards',
        avatarUrl: 'https://images.unsplash.com/photo-1494790108755-2616b612b47c?w=150&h=150&fit=crop&crop=face',
        role: 'player',
        skillLevel: 'advanced',
        rank: 'F',
        totalWins: 67,
        totalLosses: 19,
        totalTournaments: 8,
        eloRating: 2034,
        spaPoints: 3800,
        totalPrizePool: 28000000,
        isVerified: true,
        isActive: true,
        location: 'Quận 2, TP.HCM',
        createdAt: DateTime.now().subtract(const Duration(days: 300)),
        updatedAt: DateTime.now(),
      ),
    ];
  }

  /// Get random club names for demo
  static String getRandomClubName() {
    final clubs = [
      'CLB SABO ARENA',
      'CLB BILLIARDS SAIGON',
      'CLB CUE MASTER',
      'CLB CHAMPION',
      'CLB GOLDEN CUE',
      'CLB ROYAL BILLIARDS',
      'CLB ELITE PLAYERS',
    ];
    
    return clubs[(DateTime.now().millisecondsSinceEpoch % clubs.length)];
  }
}